import { StyleSheet } from 'react-native';
import { appTheme } from '../../theme/appTheme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: appTheme.colors.pageBg,
    paddingHorizontal: 16,
  },
  hero: {
    backgroundColor: appTheme.colors.cardBg,
    borderRadius: appTheme.radius.xl,
    borderWidth: 1,
    borderColor: appTheme.colors.cardBorder,
    padding: 16,
    marginBottom: 14,
    shadowColor: '#6D5DFB',
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 14,
    elevation: 3,
  },
  heroTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: appTheme.colors.textPrimary,
    marginBottom: 6,
  },
  subtitle: {
    fontSize: 14,
    color: appTheme.colors.textSecondary,
    lineHeight: 20,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  tile: {
    width: '48.3%',
    backgroundColor: appTheme.colors.cardBg,
    borderRadius: appTheme.radius.lg,
    borderWidth: 1,
    borderColor: appTheme.colors.cardBorder,
    padding: 10,
    marginBottom: 12,
    shadowColor: '#6D5DFB',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
  },
  preview: {
    height: 84,
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 10,
    justifyContent: 'flex-end',
    backgroundColor: appTheme.colors.cardBorder,
  },
  previewImage: {
    borderRadius: 12,
  },
  previewOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(52, 46, 124, 0.28)',
  },
  previewBadge: {
    margin: 8,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  previewBadgeText: {
    fontSize: 11,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  tileTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: appTheme.colors.textPrimary,
    marginBottom: 3,
  },
  tileDescription: {
    fontSize: 12,
    color: appTheme.colors.textSecondary,
    lineHeight: 17,
    minHeight: 34,
  },
  dangerButton: {
    marginTop: 2,
    backgroundColor: appTheme.colors.dangerBg,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  dangerButtonText: {
    color: appTheme.colors.dangerText,
    fontWeight: '700',
    fontSize: 14,
  },
});
