import { StyleSheet } from 'react-native';
import { appTheme } from '../../theme/appTheme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: appTheme.colors.pageBg, paddingHorizontal: 16 },
  topBar: {
    marginBottom: 14,
  },
  pageTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: appTheme.colors.textPrimary,
    marginLeft: 10,
    letterSpacing: 0.2,
  },
  card: {
    backgroundColor: appTheme.colors.cardBg,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: appTheme.colors.cardBorder,
    padding: 14,
    marginBottom: 12,
    shadowColor: '#6D5DFB',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  videoTitle: {
    flex: 1,
    fontSize: 16,
    color: appTheme.colors.textPrimary,
    fontWeight: '800',
    marginRight: 8,
  },
  levelBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: '#ECE9FF',
    borderWidth: 1,
    borderColor: '#D7D0FF',
  },
  levelBadgeText: {
    fontSize: 11,
    color: appTheme.colors.primaryDark,
    fontWeight: '700',
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
    marginBottom: 8,
  },
  metaText: {
    fontSize: 12,
    color: appTheme.colors.textSecondary,
    fontWeight: '600',
  },
  metaDot: {
    fontSize: 12,
    color: '#94A3B8',
    marginHorizontal: 6,
  },
  poseRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 10,
  },
  poseChip: {
    backgroundColor: '#EEF3FF',
    borderColor: appTheme.colors.cardBorder,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginRight: 6,
    marginBottom: 6,
    fontSize: 11,
    color: appTheme.colors.primaryDark,
    fontWeight: '600',
  },
  thumbnail: {
    height: 190,
    borderRadius: 12,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1D1B49',
    position: 'relative',
  },
  videoPreview: {
    width: '100%',
    height: '100%',
    backgroundColor: '#000000',
  },
  previewToggleButton: {
    position: 'absolute',
    right: 10,
    bottom: 10,
    backgroundColor: 'rgba(77, 67, 209, 0.80)',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.45)',
  },
  previewToggleButtonText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
  },
  previewFallback: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  previewFallbackText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  emptyText: { fontSize: 14, color: appTheme.colors.textSecondary },
});
