import { StyleSheet } from 'react-native';
import { appTheme } from '../../theme/appTheme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: appTheme.colors.pageBg, paddingHorizontal: 16 },
  topBar: { marginBottom: 6 },
  subtitle: { fontSize: 14, color: appTheme.colors.textSecondary, marginBottom: 14, lineHeight: 20 },
  searchRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  input: {
    flex: 1,
    backgroundColor: appTheme.colors.cardBg,
    borderWidth: 1,
    borderColor: appTheme.colors.cardBorder,
    borderRadius: appTheme.radius.md,
    paddingHorizontal: 12,
    paddingVertical: 11,
    color: appTheme.colors.textPrimary,
    fontSize: 14,
  },
  button: {
    backgroundColor: appTheme.colors.primary,
    borderRadius: appTheme.radius.md,
    paddingHorizontal: 14,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#6D5DFB',
    shadowOpacity: 0.18,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 14,
    elevation: 4,
  },
  buttonText: { color: '#FFFFFF', fontWeight: '700', fontSize: 13 },
  resultCard: {
    backgroundColor: appTheme.colors.cardBg,
    borderRadius: appTheme.radius.lg,
    borderWidth: 1,
    borderColor: appTheme.colors.cardBorder,
    padding: 14,
    marginBottom: 10,
    shadowColor: '#6D5DFB',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
  },
  resultTitle: { fontSize: 15, fontWeight: '700', color: appTheme.colors.textPrimary, marginBottom: 5 },
  resultMeta: { fontSize: 12, color: appTheme.colors.textSecondary, marginBottom: 3 },
  resultText: { fontSize: 13, color: appTheme.colors.textPrimary, lineHeight: 19 },
  emptyText: { fontSize: 14, color: appTheme.colors.textSecondary },
});
